AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'generate.thor'

# class Example
# ...
# private
# ...
# end
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: leading

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/gecko-ruby.rb'

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# We like neatly-aligned code
Layout/SpaceBeforeFirstArg:
  Enabled: false

# Allow single or double quotes
Style/StringLiterals:
  Enabled: false

# Disable this until we can work out how to allow aligning of assignments
# https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/style/extra_spacing_spec.rb#L23
Layout/ExtraSpacing:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
